### ISSUE TITLE
Error with any algorithm!

### ISSUE THREAD

**Issue by lexterror** [jonelo/jacksum#1] opened 2021-09-05 04:56 UTC
I'm getting the following error:

Exception in thread "Thread-1" java.lang.IllegalAccessError: tried to access method net.jacksum.multicore.manyfiles.WorkerThread$ThreadID.<init>()V from class net.jacksum.multicore.manyfiles.WorkerThread
        at net.jacksum.multicore.manyfiles.WorkerThread.<clinit>(WorkerThread.java:58)
        at net.jacksum.multicore.manyfiles.MessageWorker.run(MessageWorker.java:65)
        at java.base/java.lang.Thread.run(Unknown Source)

I have the latest 11th gen intel icore cpu (maybe that's why). Please let me know if there is something i can do about this!

**Comment by jonelo** [comment] 2021-09-05 07:30
Thank you very much for your request! Could you please let me know what operating system you are working on, and what JDK (version, vendor, etc.) you are using? Could you please run
`java -jar jacksum-3.0.0.jar --info > env.txt` and attach env.txt here?
That should tell us all the details about OS, JDK version, vendor, arch, etc.

I would like to reproduce the issue, could you please also let me know how exactly you run Jacksum? I mean the entire command line args. Thanks!

**Comment by lexterror** [comment] 2021-09-05 16:34
Hi,

The command I'm running is:

java -jar "jacksum.jar" %*

jacksum -a sha3-512 -f -F "#FINGERPRINT #FILESIZE #FILENAME" *

[-----------------------------------------
[env.txt](https://github.com/jonelo/jacksum/files/7112003/env.txt)

I'm attaching "env.txt"

Thank you!

**Comment by jonelo** [comment] 2021-09-05 20:05
Let's see ... there is nothing wrong with the command that you are running, but there is a problem with the Java Runtime Environment that you are using. In env.txt I found:
```
    java.runtime.version=11-ea+8
    ...
    java.vendor=Oracle Corporation
    ...
    java.version.date=2018-09-25
```
That is an "ea"-release, the ea stands for "early access" and it predates the official Java 11 release. Also it is almost 3 years old. I recommend to update to at least to the latest JDK within the Java 11 familiy (which is 11.0.12) or any later major LTS release (I believe Java 17 will be released in September this year).
You could download an official release from Oracle or from any other reliable provider that offers an OpenJDK. I am using the latest pre-build OpenJDK binary from the Eclipse Foundation for example which I can recommend. You can find their JDK binaries at https://adoptium.net/ 

Could you please let me know if it fixes your issue if you update to the latest Java 11 update release?

**Comment by lexterror** [comment] 2021-09-05 20:37
Hi,

It's able to hash now!  For some reason it's running in an endless "loop" now! (It keeps hashing the same files infinitely!

Is there something wrong with my command? Also: isn't my command supposed to print the hashes to a file?

Thank you!

**Comment by jonelo** [comment] 2021-09-05 21:22
I am glad that the first issue has been resolved by updating your JDK.
Could you please open a new ticket for the next problem so we can track issues separately?

Thanks,
Johann

**Comment by jonelo** [comment] 2021-09-05 22:22
closing this issue because it has been resolved by updating the JDK.

**Closed by jonelo** 2021-09-05 22:22 UTC
Labels: support request, solved, not a bug
